### ISSUE TITLE
Add support for anchira

### ISSUE THREAD

**Issue by mrreal100** [HDoujinDownloader/HDoujinDownloader#262] opened 2023-10-22 00:47 UTC
https://anchira.to/about

New site.

**Comment by edu5ardo** [comment] 2023-10-24 08:41
Please add https://anchira.to/
Thanks in advance

**Comment by RedRain77** [comment] 2023-11-19 20:25
I'd like to suggest adding this website to the list. It contains both original and resampled images. However, there's a mechanism in place that compiles the archives on the site before they are downloadable. Is there a known method to bypass this? Specifically, I'm looking for a way to access the original images without relying on the default script used for packaging the archives.

**Comment by septimsignum** [comment] 2023-12-10 15:45
I also would like to request that this site be added to @HDoujinDownloader , or _re_-added technically (as it was formerly ksk.moe).

**Comment by Romangelo** [comment] 2024-02-08 20:29
Yes, please add support for this site. It has great content that aren't available elsewhere.

**Comment by HDoujinDownloader** [comment] 2024-04-14 02:40
This site has now been added, and should be working the next time you restart HDoujin Downloader!

**Comment by septimsignum** [comment] 2024-04-14 04:51
@HDoujinDownloader - Glad to hear it. Gave it a shot as soon as I heard, however I got the following error

```
23:49:30 page grabber [x] Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.
   at _q9r6nRJwen9YnurnWpXCHjAB3gC._vt775j1qa9beSMmCaXXKwoW0PwC(IEnumerable`1 , _XeMwTipI9eKUadrfL1vmo2Nc7yP , _lVKipORwtAx8v9LaNaTr6FYzFEB ) at _qYJayOJOS1m9HoHULYr2rZaSfeG._FIXsbjNihh0eL3fEyTbcJL4v8bsA(String& )
```

**Comment by HDoujinDownloader** [comment] 2024-04-14 07:04
Thanks for the report-- Would you be willing to send me the link you tried to add to the queue?

**Comment by edu5ardo** [comment] 2024-04-14 07:07
There is some limitation to the download? since it tells me "error page collection" after a few downloads

**Comment by septimsignum** [comment] 2024-04-14 14:43
@HDoujinDownloader Sent it over via the [contact](https://doujindownloader.com/contact/) page. Unless you want me to post it here? (wasn't sure if you wanted it direct or not...)

**Comment by HDoujinDownloader** [comment] 2024-04-14 16:33
@septimsignum Thank you for that.

Try adding the URL with "https://" instead of "http://". The latter makes it access Anchira's API over HTTP as well which causes problems when it redirects back to HTTPS. I'll fix this later.

@edu5ardo I noticed that it occasionally shows a captcha when accessing the reader, but I haven't confirmed if HDoujin Downloader is affected by this. I solved the captcha in my browser and haven't encountered any problems since. Let me know if this seems relevant to your issue; I might add a warning for when this occurs.

**Comment by septimsignum** [comment] 2024-04-14 16:47
@HDoujinDownloader ...didn't realize the link i gave you had 'http://'. When I added the URL originally it was an 'https://' URL. Tried clearing and requeuing it - same error.  When I pulled the URL from the downloader, it showed as an 'http://'.

**Comment by edu5ardo** [comment] 2024-04-14 17:10
@HDoujinDownloader I really don't know if the captcha is relevant, I don't really know how to check it, but hdoujin allows you to download between 3 and 4 links before blocking for 5 or 6 hours, then I can continue some more downloads manually by pausing and starting the downloads

**Comment by HDoujinDownloader** [comment] 2024-04-15 00:09
@septimsignum Do you happen to have "Force downgrade to HTTP" enabled under **_Tools > General settings > Network_**?

@edu5ardo I've done some more testing now and noticed the same thing-- I start getting 403 errors after making more than a few API requests. I can start downloading again immediately if I open any gallery in their reader and solve the captcha that appears.

**Comment by septimsignum** [comment] 2024-04-15 01:09
@HDoujinDownloader Ah, apparently I did....no idea how/why/when but *shrug* and turning that off fixed things (aside from the other limitation noted above)

**Comment by HDoujinDownloader** [comment] 2024-05-25 04:49
I'm going to close this issue since the site is now supported, although it stopped working at the moment. Discussion will continue in #345.

**Closed by HDoujinDownloader** 2024-05-25 04:49 UTC
Labels: enhancement, website
