### ISSUE TITLE
nhentai.net: Requests blocked by Cloudflare

### ISSUE THREAD

**Issue by bubbee23** [HDoujinDownloader/HDoujinDownloader#144] opened 2022-08-28 12:02 UTC
I can't download from nhentai after status "waiting for cloudflare" and in queue list show nhentai.net replace manga name.
 2 days ago this domain can download normally.

![Screenshot (2)](https://user-images.githubusercontent.com/74089129/187073185-f9fcf0d7-25b2-49e3-a292-72f4cc85577c.png)

![image](https://user-images.githubusercontent.com/74089129/187073194-bb4b5199-3c85-402b-bfa1-b56936a93689.png)

**Comment by HDoujinDownloader** [comment] 2022-09-01 07:54
As you've noticed, the problem is related to Cloudflare's new "checking if the site connection is secure" page. It used to be possible to bypass this using the [FlareSolverr plugin](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver), but FlareSolverr is currently unable to process Cloudflare's new page.

The FlareSolverr devs are aware of it, and there is an open issue discussing the problem: FlareSolverr/FlareSolverr#481

For now, we'll just have to wait for a new FlareSolverr update!

**Comment by Romangelo** [comment] 2022-09-03 15:22
They're taking so long to update though.

**Comment by HDoujinDownloader** [comment] 2022-09-04 04:55
@Romangelo Yes, it is taking a while for a fix to become available, but all we can do is wait for now.

I am continuing to explore other options for getting around it, but chances are FlareSolverr will be fixed before I have anything else fully implemented.

**Comment by Romangelo** [comment] 2022-09-06 19:41
Is it possible to add a new feature for HDoujinDownloader, make it pretends to be a web browser, and let the user solve cloudflare ourselves? With this, we'll never have to deal with Cloudflare's update anymore.

**Comment by hamkah2c** [comment] 2022-09-10 23:12
> Is it possible to add a new feature for HDoujinDownloader, make it pretends to be a web browser, and let the user solve cloudflare ourselves? With this, we'll never have to deal with Cloudflare's update anymore.

its already exist for manual detection, but for some reason its doesn't work anymore
![image](https://user-images.githubusercontent.com/8862875/189504761-1814c881-d15a-4c2c-9564-131b82949a08.png)


 log : 
[1662849894-debug.log](https://github.com/HDoujinDownloader/HDoujinDownloader/files/9541526/1662849894-debug.log)

**Comment by ilike2burnthing** [comment] 2022-09-12 02:19
[v2.2.7](https://github.com/FlareSolverr/FlareSolverr/releases/v2.2.7) now out.

**Comment by MimoKar** [comment] 2022-09-13 13:11
Seems working now with new version.

**Comment by Phamine** [comment] 2022-09-14 15:59
Can confirm 1337x now working with the update

**Comment by unnes** [comment] 2022-09-17 19:13
Can someone explain how to update HDoujinDownlader with the new version of FlareSolverr? I don't see a drop-in replacement anywhere obvious.

**Comment by trestlesky** [comment] 2022-09-19 19:06
Mine still fails, something I need to update in HDoujin Downloader settings?

**Comment by HDoujinDownloader** [comment] 2022-09-20 00:04
I can confirm the issue is resolved with [FlareSolverr v2.2.8](https://github.com/FlareSolverr/FlareSolverr/releases/download/v2.2.8/flaresolverr-v2.2.8-windows-x64.zip). 🎉

See [here](https://github.com/HDoujinDownloader/HDoujinDownloader/wiki/FlareSolverr-IUAM-Challenge-Solver#updating-the-flaresolverr-plugin) for instructions explaining to update the plugin (tl;dr: just plop the new version of FlareSolverr in your `plugins/` folder).

**Closed by HDoujinDownloader** 2022-09-20 00:04 UTC
Labels: bug, website
