### ISSUE TITLE
Add support for h5.mangatoon.mobi

### ISSUE THREAD

**Issue by deanwinch1** [HDoujinDownloader/HDoujinDownloader#91] opened 2022-03-17 11:49 UTC
- Site: https://h5.mangatoon.mobi/
- Manga List: https://h5.mangatoon.mobi/
- Manga example: https://h5.mangatoon.mobi/contents/detail/5
- Chapter online viewer example: https://h5.mangatoon.mobi/cartoons/watch/5/108302

Languages
- English

- It is an alternative domain of [Manga Toon](https://mangatoon.mobi/).

**Comment by HDoujinDownloader** [comment] 2022-03-18 01:56
Duplicate of #71.

**Closed by HDoujinDownloader** 2022-03-18 01:56 UTC
Labels: duplicate, enhancement, extractors
